nome = input("Digite um funcionário: ")
empresa = input("Digite a instituição: ")
qtde_funcionarios = int(input("Digite a quantidade de funcionários: "))
mediaMensalidade = float( input("Digite a média da mensalidade: "))
print(f"{nome} trabalha na empresa {empresa}")
print(f"Possui {qtde_funcionarios} funcionários")
print(f"A média da mensalidade é de {str(mediaMensalidade)}")
print("===== Verifique os tipos de dados abaixo: =====")
print(f"O tipo de dado da variável [nome] é {type(nome)}")
print(f"O tipo de dado da variável [empresa] é {type(empresa)}")
print(f"O tipo de dado da variável [qtde_funcionarios] é {type(qtde_funcionarios)}")
print(f"O tipo de dado da variável [mediaMensalidade] é {type(mediaMensalidade)}")
